language: python
python:
  - "2.7"

install: 
 - "pip install -r requirements.txt"
 - "pip install -r requirements-dev.txt"
script: nosetests test

notifications:
  irc:
    channels:
      - "irc.freenode.net#scoundrels"
    on_success: change # [always|never|change] # default: change
    on_failure: always # [always|never|change] # default: always
