#!/bin/bash    
# Scrib update script ver. 0.2
# by KittyTristy "Tristy Hopkins"

## Our Variables! ##
CORE=0.7.2
BRAIN=0.1.0
DATE=$(date +"%x %r %Z")
BOLD="\e[1m"
CLEAR="\e[0m"

## Our functions! ##
function update
{
	echo -e $BOLD"You're about to push the current Scrib code to Github."$CLEAR
	sleep 1

		while true; do
			read -p "Continue? [Yes/No]" yn
			case $yn in
			[Yy]* ) (upver); exit;;
			[Nn]* ) exit ;;
			* ) echo "Please enter yes or no.";;
			esac
		done
}

## Push or pull to Github? (in progress)
#function pushorpull
#{
#	echo -e $BOLD"Would you like to push or pull?"$CLEAR
#	sleep 1
#
#		while true; do
#			read -p "> "
#			case 

function upver
{
	echo -e $BOLD"We'll now setup your commit!"$CLEAR
	sleep 1
	while true; do
		read -p "Update version? [Yes/No]" yn
		case $yn in
		[Yy]* ) (version); (push); exit ;;
		[Nn]* ) (push); exit ;;
		* ) echo "Please enter Yes or No.";;
		esac
	done
}

function version
{
	echo -e $BOLD"Enter the core version number for this Scrib."$CLEAR
	read -e -p "# " CORE

	echo -e $BOLD"Okay, now enter the brain version."$CLEAR
	read -e -p "# " BRAIN

	echo "Creating new VERSION file.."

	# Building the new VERSION file!
	rm -rf VERSION
	cat >> VERSION <<- _EOF_
	# Core version of Scrib #
	core= '$CORE'
	# Brain version of Scrib #
	brain= '$BRAIN'
	# Date of last update #
	date= '$DATE'
	_EOF_

}

function push
{

	echo ""
	git status
	echo ""

	echo -e $BOLD"Please enter the files you'd like to add to this commit."$CLEAR
	sleep 1
	read -p "# " LIST
	echo ""
	git add $LIST
	sleep 1

	echo -e $BOLD"Enter the message you'd like to include with this commit."$CLEAR
	read -p "# " MESSAGE
	git commit -m "$MESSAGE"
	echo ""

	echo -e $BOLD"Okay, looks like we're ready to push to Github."$CLEAR
	sleep 1
	echo "Commencing push.."
	sleep 1
	git push origin master

	echo ""
	echo -e $BOLD"And we're done.  Have a good day, human."$CLEAR
}

function reset
{
	echo -e "\e[0m"
}

## The bit that starts everything! ##
update

## Let's not leave behind any stray color codes when terminated! ##
trap reset SIGHUP SIGINT SIGTERM

